### ISSUE TITLE
Sasviya 3.5  After patched     service  can't not  start 

### ISSUE THREAD

**Issue by 2015eva** [sassoftware/loguccino#18] opened 2022-01-15 17:02 UTC
Sasviya 3.5  After patched  sas-viya-cachelocator-default   service  can't not  start 

see the error message 
https://imgur.com/a/mfVRVUz

https://imgur.com/a/YOUcN2J

**Comment by boemska-nik** [comment] 2022-01-17 20:01
Please raise this issue with SAS Support directly, they should be able to assist you. I'll leave this issue open while they replicate the problem on their side.

**Comment by boemska-nik** [comment] 2022-01-31 19:57
Hi @2015eva - the latest release preserves the order in which files are added back into the patched archive, solving some of the classloader issues caused by the previous repackaging strategy. I'm going to close this. If the problem persists please feel free to reopen it.

**Closed as completed by boemska-nik** 2022-01-31 19:57 UTC
Labels: triaging
